{
 "title": "Todo App Production Monitoring",
 "tags": [
  "devops",
  "nodejs",
  "todoapp"
 ],
 "panels": [
  {
   "title": "🖥️ ÉTAT DE SANTÉ SYSTÈME (NODE.JS EXPRESS)",
   "type": "row",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "⚡ Charge CPU Globale",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode!=\"idle\"}[1m]) * 100",
     "legendFormat": "Usage CPU Hôte"
    }
   ]
  },
  {
   "title": "💾 Allocation Mémoire (RAM Node.js)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_rss_bytes",
     "legendFormat": "Taille de la RAM utilisée (RSS)"
    },
    { "expr": "node_memory_heap_total_bytes", "legendFormat": "Taille totale du Heap Node" }
   ]
  },
  {
   "title": "📡 MÉTRIQUES RÉSEAU & APPELS API (TRAFIC)",
   "type": "row",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 }
  },
  {
   "title": "📊 Débit Global (Req / Sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "Requêtes totales / Sec"
    }
   ]
  },
  {
   "title": "🚨 Erreurs HTTP 5xx (Serveur)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(http_requests_total{status_code=~\"5..\"})",
     "legendFormat": "Erreurs 5xx"
    }
   ]
  },
  {
   "title": "⏱️ Latence de l'API (Temps de réponse)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[1m])) / sum(rate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "Temps de réponse moyen"
    }
   ]
  }
 ]
}